# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.27)
{
  # A helpful description of your flake
  description = "OpenCode extension manager with portable, isolated profiles. Your setup, anywhere.";

  # Flake inputs
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*";

    # Provides the Bun setup hook and fetchBunDeps used to install npm
    # dependencies reproducibly (offline) inside the Nix build sandbox.
    bun2nix = {
      url = "github:nix-community/bun2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # Flake outputs that other flakes can use
  outputs = { self, flake-schemas, nixpkgs, bun2nix }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" "aarch64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
        bun2nix = bun2nix.packages.${system}.default;
      });

      ocxVersion = "2.0.11";

      # Builds the OCX CLI from source, mirroring the AUR PKGBUILD:
      #   prepare()  -> bun install --frozen-lockfile
      #   build()    -> (cd packages/cli && bun run build)
      #   check()    -> bun run check  (+ a `ocx --help` smoke test)
      #   package()  -> install dist/index.js to /usr/bin/ocx
      # Dependency installation is handled by `bun2nix.hook`, which populates
      # Bun's install cache from a fixed-output derivation so the build stays
      # pure and works inside Nix's network-isolated sandbox.
      ocxFor = { pkgs, bun2nix }: pkgs.stdenv.mkDerivation (finalAttrs: {
        pname = "ocx";
        version = ocxVersion;

        # The fetched upstream source, with the generated `bun.nix` manifest
        # dropped in at the root. `bun.nix` references workspace paths relative
        # to itself (`./packages/cli`, `./workers/kdco-registry`), so it must
        # live inside the source tree.
        src = pkgs.runCommand "ocx-${finalAttrs.version}-src" { } ''
          cp -r ${pkgs.fetchFromGitHub {
            owner = "kdcokenny";
            repo = "ocx";
            tag = "v${finalAttrs.version}";
            hash = "sha256-rr10tlPlfhFs07zRYakWG2OmNoOqyrSw393ky7DFTbM=";
          }} $out
          chmod -R u+w $out
          install -m644 ${./bun.nix} $out/bun.nix
        '';

        nativeBuildInputs = with pkgs; [
          bun
          git
          makeWrapper
          bun2nix.hook
        ];

        bunDeps = bun2nix.fetchBunDeps {
          bunNix = "${finalAttrs.src}/bun.nix";
        };

        # Hoisted linker matches how the project installs outside of Nix and
        # avoids the symlink/isolated-install quirks Bun has on macOS.
        bunInstallFlags = [
          "--linker=hoisted"
        ];

        # Leave the `#!/usr/bin/env -S bun --no-env-file` shebang on the bundled
        # CLI alone; coreutils' `env` does not understand `-S`. We invoke the
        # built script through a wrapper below instead.
        dontPatchShebangs = true;

        # The hook runs `bun install` (using the prebuilt cache) in
        # `bunNodeModulesInstallPhase`, before the standard build phase.
        buildPhase = ''
          runHook preBuild

          bun run --cwd packages/cli build

          runHook postBuild
        '';

        checkPhase = ''
          runHook preCheck

          # Type-check and lint the whole workspace, then smoke-test the built
          # CLI to confirm it boots under Bun.
          bun run check
          bun packages/cli/dist/index.js --help

          runHook postCheck
        '';

        installPhase = ''
          runHook preInstall

          install -Dm644 LICENSE "$out/share/licenses/ocx/LICENSE"
          install -Dm755 packages/cli/dist/index.js "$out/lib/ocx/index.js"
          makeWrapper ${pkgs.bun}/bin/bun "$out/bin/ocx" \
            --add-flags "$out/lib/ocx/index.js"

          runHook postInstall
        '';

        meta = {
          description = "OpenCode extension manager with portable, isolated profiles. Your setup, anywhere.";
          homepage = "https://github.com/kdcokenny/ocx";
          license = pkgs.lib.licenses.mit;
          mainProgram = "ocx";
          platforms = pkgs.lib.platforms.unix;
        };
      });
    in {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      # Packages
      packages = forEachSupportedSystem ({ pkgs, bun2nix }: {
        ocx = ocxFor { inherit pkgs bun2nix; };
        default = ocxFor { inherit pkgs bun2nix; };
      });

      # Development environments
      devShells = forEachSupportedSystem ({ pkgs, ... }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [
            nixpkgs-fmt
          ];
        };
      });
    };
}